default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: db

development:
  <<: *default
  database: book_log_list_development

test:
  <<: *default
  database: book_log_list_test

production:
  <<: *default
  database: book_log_list_production
  username: book_log_list
  password: <%= ENV['BOOK_LOG_LIST_DATABASE_PASSWORD'] %>